ALTER TABLE conversation.conversations
  ADD COLUMN IF NOT EXISTS environment text NOT NULL DEFAULT 'live'
  CHECK (environment IN ('live', 'test'));

-- Every conversation that existed before this migration was generated by the
-- local demo/seed workflow. Keep it out of the production inbox.
UPDATE conversation.conversations SET environment = 'test';

ALTER TABLE conversation.conversations
  DROP CONSTRAINT IF EXISTS conversations_organization_id_channel_account_id_external_thread_id_key;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'uq_conversations_thread_environment'
      AND conrelid = 'conversation.conversations'::regclass
  ) THEN
    ALTER TABLE conversation.conversations
      ADD CONSTRAINT uq_conversations_thread_environment
      UNIQUE (organization_id, channel_account_id, environment, external_thread_id);
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_conversations_environment_inbox
  ON conversation.conversations(organization_id, environment, last_message_at DESC);

CREATE TABLE IF NOT EXISTS catalog.course_facts (
  course_id uuid PRIMARY KEY REFERENCES catalog.courses(id) ON DELETE CASCADE,
  organization_id uuid NOT NULL REFERENCES iam.organizations(id),
  source_name text,
  course_type text,
  combo_name text,
  learning_modes text[] NOT NULL DEFAULT '{}',
  offline_regions text[] NOT NULL DEFAULT '{}',
  next_start_date date,
  schedule_detail text,
  early_bird_slots text,
  course_url text,
  audience_profile text,
  experience_sharing text,
  certificate_condition text,
  curriculum_text text,
  curriculum_image text,
  assignment_info text,
  installment_info text,
  retake_policy text,
  trainer_info text,
  has_record text,
  source_metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE catalog.offerings ADD COLUMN IF NOT EXISTS source_key text;
CREATE UNIQUE INDEX IF NOT EXISTS uq_offerings_source_key
  ON catalog.offerings(organization_id, source_key) WHERE source_key IS NOT NULL;

ALTER TABLE pricing.rules ADD COLUMN IF NOT EXISTS group_price numeric(16,2);
ALTER TABLE pricing.rules ADD COLUMN IF NOT EXISTS alumni_price numeric(16,2);
ALTER TABLE pricing.rules ADD COLUMN IF NOT EXISTS installment_info text;
ALTER TABLE pricing.rules ADD COLUMN IF NOT EXISTS note text;
ALTER TABLE pricing.rules ADD COLUMN IF NOT EXISTS offline_regions text[] NOT NULL DEFAULT '{}';
ALTER TABLE pricing.rules ADD COLUMN IF NOT EXISTS course_type text;
ALTER TABLE pricing.rules ADD COLUMN IF NOT EXISTS combo_name text;
ALTER TABLE pricing.rules ADD COLUMN IF NOT EXISTS source_key text;
CREATE UNIQUE INDEX IF NOT EXISTS uq_pricing_rules_source_key
  ON pricing.rules(organization_id, source_key) WHERE source_key IS NOT NULL;

CREATE TABLE IF NOT EXISTS platform.import_runs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL REFERENCES iam.organizations(id),
  import_type text NOT NULL CHECK (import_type IN ('courses', 'pricing')),
  filename text NOT NULL,
  status text NOT NULL CHECK (status IN ('completed', 'failed')),
  summary jsonb NOT NULL DEFAULT '{}'::jsonb,
  errors jsonb NOT NULL DEFAULT '[]'::jsonb,
  created_by uuid REFERENCES iam.users(id),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_import_runs_recent
  ON platform.import_runs(organization_id, created_at DESC);

DROP TRIGGER IF EXISTS trg_course_facts_updated ON catalog.course_facts;
CREATE TRIGGER trg_course_facts_updated
  BEFORE UPDATE ON catalog.course_facts
  FOR EACH ROW EXECUTE FUNCTION platform.touch_updated_at();
